TARGET=	swap selection bubble qsort
pointConcept endian pointer2 functionPointer
voidPointer arrayPointer arrayAssignment
arrayCompare arrayFunction sumArrayFunction
sumMatrixFuction 




all: ${TARGET}

swap:	$@
selection: $@
bubble:	$@
qsort:	$@
pointConcept:	$@
endian:	$@
pointer2:	$@
functionPointer:	$@
voidPointer:	$@
arrayPointer:	$@
arrayAssignment:	$@
arrayCompare:	$@
arrayFunction:	$@
sumArrayFunction:	$@
sumMatrixFuction:	$@



clean :
	rm ${TARGET}

