TARGET=	swap selection bubble qsort
pointConcept endian pointer2 functionPointer
voidPointer arrayPointer arrayAssignment
arrayCompare arrayFunction sumArrayFunction
sumMatrixFuction serial hellowStr
charPointerOperation strcatExemple

all: ${TARGET}

swap:	$@
selection: $@
bubble:	$@
qsort:	$@
pointConcept:	$@
endian:	$@
pointer2:	$@
functionPointer:	$@
voidPointer:	$@
arrayPointer:	$@
arrayAssignment:	$@
arrayCompare:	$@
arrayFunction:	$@
sumArrayFunction:	$@
sumMatrixFuction:	$@
serial:	$@
hellowStr:	$@
charPointerOperation:	$@
strcatExemple:	$@





clean :
	rm ${TARGET}

