TARGET=infinit limit celsisus2fahr 
fahr2celsius charNumber triangle 
triangle2 arithmetic increment 
literal genderRatio compare sizeof
fourBit oddeven fourBit2

all: ${TARGET}

infinit : $@
limit : $@
celsisus2fahr :$@
fahr2celsius :$@
charNumber: $@
triangle: $@
triangle2: $@
arithmetic:$@
increment:$@
literal: $@
genderRatio: $@
compare: $@
sizeof: $@
oddeven: $@
fourBit: $@
fourBit2: $@
clean :
	rm ${TARGET}

