TARGET=infinit limit celsisus2fahr fahr2celsius charNumber 
triangle triangle2 arithmetic 
increment literal

all: ${TARGET}

infinit : $@
limit : $@
celsisus2fahr :$@
fahr2celsius :$@
charNumber: $@
triangle: $@
triangle2: $@
arithmetic:$@
increment:$@
literal: $@
clean :
	rm ${TARGET}

