TARGET=infinit limit celsisus2fahr 
fahr2celsius charNumber triangle 
triangle2 arithmetic increment 
literal genderRatio compare sizeof

all: ${TARGET}

infinit : $@
limit : $@
celsisus2fahr :$@
fahr2celsius :$@
charNumber: $@
triangle: $@
triangle2: $@
arithmetic:$@
increment:$@
literal: $@
genderRatio: $@
compare: $@
sizeof: $@
clean :
	rm ${TARGET}

