TARGET=absolute leePYear passFail 
grade grade2 posZeroNeg posZeroNeg2
posZeroNeg3 bigtest onetoTen one2tensum
multiTable ascii star one2tenwhile
one2TenDoWhile

all: ${TARGET}

absolute: $@
leePYear: $@
passFail: $@
grade: $@
grade2: $@
posZeroNeg: $@
posZeroNeg2: $@
posZeroNeg3: $@
bigtest: $@
oneToten: $@
one2tensum: $@
multiTable: $@
ascii: $@
star: $@
one2tenwhile: $@
one2TenDoWhile: #@


clean :
	rm ${TARGET}

